freeze_bert_parameters:
  val: 1
  desc: Freeze the parameters of bert.

warmup_proportion:
  val: 0.1
  desc: The warmup ratio for learning rate. | (float)

mlp_hidden:
  val: 64
  desc: mlp
wait_patient:
  val: 10
  desc: Early stop strategy.
z_dim:
  val: 64
  desc: Sentence embedding dimension.
need_ind:
  val: 1
  desc: Whether the data set output index.
loop_nums:
  val: 100
  desc: The warmup ratio for learning rate.
loss_type:
  val: pml
  desc: The warmup ratio for learning rate.
use_pretrain:
  val: 1
  desc: Whether to freeze all parameters but the last layer.